### ISSUE TITLE
Make API Server for whatsapp-scraper

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/whatsapp-scraper#11]
Task Overview : 
1. Create a strapi app at the src/api directory
2. Create Content types for WhatsApp Group and WhatsApp Message 
3. Make api call from the app you wrote at src/scraper to the strapi server to store groups and messages scraped

The server needs to support the following APIs
- returns a list of all whatsapp groups
- returns a list of all whatsapp messages within a group
- add a group
- add a message to a group
- delete a message to a group
- add tags to a message (we might also need a Tag content type)
- an API to link two messages within a same group

**Comment by surajsharma** [comment]
this can be closed this as the API is ready with the custom routes (for those requests which I felt would slow down at scale) in the latest commit. the rest of the functionality is out-of-the-box with strapi.

**Comment by dennyabrain** [comment]
@surajsharma can  you make a PR and link it to this issue?

**Comment by surajsharma** [comment]
@dennyabrain cannot create a new PR on the same branch while there is one existing.
