### ISSUE TITLE
anonymize numbers of chat conversation

### ISSUE THREAD

**Issue by tarunima** [tattle-made/whatsapp-scraper#21]
Content extracted from a chat conversation must be anonymized before being added to Tattle's database. 

This would involved replacing the phone number with a randomly generated ID. For any exported file, a number should be mapped to an ID. This will help in identifying connected messages on a WhatsApp UI. The ID does not need to be unique across exported files. 

Some anonymization techniques are here: https://piwik.pro/blog/the-ultimate-guide-to-data-anonymization-in-analytics/

This step should be carried out as soon as the file is exported into a database which allows for field substitution and prior to any other processing.

**Comment by surajsharma** [comment]
Closing as this is implemented. We hash the phone numbers before uploading then substitute the hashes on the front-end with randomly generated names. The client never receives a single phone number nor are any stored in the db. The hash is reversible using a secret key.
