### ISSUE TITLE
Project Structure Discussion

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/whatsapp-scraper#3]
I am proposing the following structure for the current sprint.
<img width="691" alt="Screen Shot 2020-06-17 at 6 17 10 PM" src="https://user-images.githubusercontent.com/1415361/84899865-e201bf80-b0c6-11ea-822a-d918b836efa0.png">

Three main components are planned as of now
1. Express App - this server is responsible for scraping whatsapp data dump from google drive (defined [here](https://github.com/tattle-made/whatsapp-scraper/issues/2)) and from a zip file upload
2. Strapi App 
3. Web UI for the tattle team to moderate the scraped content

**Comment by surajsharma** [comment]
Much of this is done, closing
